import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { useRouter } from "next/router";
import Loader from "../components/Loader";
import StartComponent from "../components/StartComponent";
import React, {useState} from 'react';

const Home: NextPage = (props) => {

  const [loading, setLoading] = useState(true);

  React.useEffect(() => {
    // simulate a long loading process
    setTimeout(() => {
      setLoading(false);
    }, 3500);
  }, []);
  
  return (
    <>
     <Head>
        <title>My Beauty Parlor</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {loading ? <Loader /> : <StartComponent />}
      
    </>
  );
};

export default Home;
